### ISSUE TITLE
[bug] dll version not injecting to client since 0.2.3

### ISSUE THREAD

**Issue by Jacbo1** [100PXSquared/VisTrace#11]
The dll version does not inject to the client since 0.2.3. Only the workshop version works after that which restricts its use to singleplayer unless you can convince a server owner to add it.

**Comment by 100PXSquared** [comment]
Not a bug, however injection can be re-added easily as a backup.

**Comment by 100PXSquared** [comment]
Added in e0baa6f1658b192cd4d0a9d9edf3e6f92dd2b143
